require("user.options")
require("user.plugins")
require("user.harpoon")
require("user.keymaps")
require("user.colorscheme")
require("user.cmp")
require("user.navbuddy")
require("user.lsp")
require("user.telescope")
require("user.gitsigns")
require("user.treesitter")
require("user.autopairs")
require("user.comment")
require("user.neotree")
require("user.toggleterm")
require("user.impatient")
require("user.indentline")
require("user.alpha")
require("user.whichkey")
require("user.autocommands")
require("user.smallplugins")
-- require("user.tasks")
require("user.copilot")
-- require("user.flutter")
-- vim.api.nvim_set_hl(0, "NeoTreeFloatBorder", { link = "Substitute" })
