-- local project_name = vim.fn.fnamemodify(vim.fn.getcwd(), ":p:h:t")
--
-- local workspace_dir = "/Users/drew/programs/minecraft/data_dir"
--
-- local config = {
-- 	cmd = { "/Users/drew/bin/jdtls/bin/jdtls", "-data", workspace_dir },
-- 	root_dir = vim.fs.dirname(vim.fs.find({ "gradlew", ".git", "mvnw", "pom.xml" }, { upward = true })[1]),
-- }
-- require("jdtls").start_or_attach(config)
